name = "meltan-404-relay"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_USERS = "850654509"
ALLOWED_CHATS = ""

[[kv_namespaces]]
binding = "BOT_MEMORY"
id = "77dde814062748b5b4ffe7fd3690d16c"
